### ISSUE TITLE
click taskbar corner date & time, the win11 style calendar always crash

### ISSUE THREAD

**Issue by chuck00000** [bbmaster123/10SM#9] opened 2022-01-21 11:34 UTC
Did I miss replace some files? the win11 style calendar always crash , I can't see Win11 notification center messages, the notification banners doesn't  pop out 

Also , after replacing the AppResolver.dll file, the UWP Software icons don't show on the taskbar ,  even opened UWP software on Taskbar don't have labels, display blank. Don't replacing the AppResolver.dll file, display UWP icons on taskbar is normal

**Comment by bbmaster123** [comment] 2022-01-21 17:27
I can confirm that if no files were accidentally missed, the calendar and notification center should be 100% fine, as well as UWP apps on the taskbar on build .438.

double check the datestamps on all the files maybe, its pooooosible one or two files didn't get replaced by accident?
let me know if its still not working correctly after! cheers :)

**Comment by chuck00000** [comment] 2022-01-22 02:07
what's the file exactly possibly cause this problem? I make sure I replaced everything  in the " files " category , Action center  & fullscreen start menu works fine , action center is still popped out windows 11 control style , click taskbar date & time  calendar crashed , notification center isn't working, even the notification banners didn't pop out

**Comment by chuck00000** [comment] 2022-01-22 04:36
when I go to win11 settings, go to Personalization → start , the whole settings app crashed, I used lastest Dev version 22538

**Comment by bbmaster123** [comment] 2022-01-22 05:15
that sounds to me like the issue involves Windows.UI.ShellCommon.pri, can you confirm the timestamp and file size on that file? 
do you run any other programs that hook into the windows shell?  On a fresh install this should work fine, so think of things that could potentially interfere. for example I've had certain specific issues with windows 10 in the past when stardock window blinds was installed. I remember on that computer I had to uninstall the program, do what I needed, and then reinstall the program after. 

BTW action center will still be windows 11 style with this, I have not yet published a reliable way to get the windows 10 action center working yet, though it is still possible on build .438 and mostly works. I only know of 2 bugs with it right now, but I don't have a ton of time to test exactly which files you'll need at the moment. 10SM may eventually add that in as a separate option for those who want. Once the slow exit bug is fixed that is.

**Comment by chuck00000** [comment] 2022-01-23 09:51
it's seems not this file cause,  thank you for replying

**Comment by bbmaster123** [comment] 2022-01-23 21:42
I'm sorry its not working for you, I don't know what the issue could be... but if you figure it out I'd be interested to hear what the issue was! 
good luck! :)

**Comment by huangsijun17** [comment] 2022-01-24 03:10
> it's seems not this file cause, thank you for replying

I also have this problem on my system. If this could be an issue with the Windows.UI.ShellCommon.pri file, then I suspect it has something to do with the Simplified Chinese Windows I'm using. 
Which Windows language are you using?

**Comment by chuck00000** [comment] 2022-01-24 08:59
> 

English (United States)

**Comment by chuck00000** [comment] 2022-01-24 08:59
> > it's seems not this file cause, thank you for replying
> 
> I also have this problem on my system. If this could be an issue with the Windows.UI.ShellCommon.pri file, then I suspect it has something to do with the Simplified Chinese Windows I'm using. Which Windows language are you using?

English (United States)

**Comment by bbmaster123** [comment] 2022-01-24 18:47
> I also have this problem on my system. If this could be an issue with the Windows.UI.ShellCommon.pri file, then I suspect it has something to do with the Simplified Chinese Windows I'm using. Which Windows language are you using?

interesting thought, I'm not sure in chuck00000's case, but in your case you could be right. the second pri file in this repo is Windows.UI.ShellCommon.en-us.pri. I think you might have, but did you already try swapping it for the one for your system language? I think CN-something, sorry not sure off the top of my head, not a Chinese language speaker

**Comment by huangsijun17** [comment] 2022-01-25 02:24
> > I also have this problem on my system. If this could be an issue with the Windows.UI.ShellCommon.pri file, then I suspect it has something to do with the Simplified Chinese Windows I'm using. Which Windows language are you using?
> 
> interesting thought, I'm not sure in chuck00000's case, but in your case you could be right. the second pri file in this repo is Windows.UI.ShellCommon.en-us.pri. I think you might have, but did you already try swapping it for the one for your system language? I think CN-something, sorry not sure off the top of my head, not a Chinese language speaker

`zh-cn` [I PR the language files.](https://github.com/bbmaster123/10SM/pull/12)

**Comment by bbmaster123** [comment] 2022-01-25 18:24
thanks for sharing!

> Windows.UI.ShellCommon.pri and Windows.UI.ShellCommon.en-US.pri needs to be restored to restore the notif center functionality.

yes, both files need to be swapped since... uh... release? Can't remember specifically which build anymore, but its been a while.  Swapping just the 1 file since that build causes issues like mentioned in the readme. But why would you not replace the entire set of given files lol I would never say replace both files but only restore the 1 hahaha 

> What's interesting is that, even with a fresh install (not really, just sfc/scannow which restores Win11 start menu and everything) if I install Stardock's Start11, the taskbar's pinned apps' right-click functionality gets broken there as well, whilst the rest works as intended

sfc /scannow is a great tool and does a terrific job, but its not always perfect. I've seen it miss files. If its still broken for you right now, please double check sfc actually did restore all the files you had replaced. 

On my end, I've been able to get everything to be able to work together, start menu, notification center, right click, pin/unpin, etc, but then to be fair the last time I tested this on a fresh install was build .376 a few weeks ago, which is now updated to build .438.  I'll have to do a test on a fresh install again soon, probably on the next stable build if I have time. Also thinking of making an install/demo vid to throw up on youtube with some of that shitty roalty-free music while I'm at it haha

cheers!

**Comment by shantanub08** [comment] 2022-01-25 18:59
> But why would you not replace the entire set of given files lol I would never say replace both files but only restore the 1 hahaha

Sorry for not explaining that part. The reason why I only used to replace that one file `Windows.UI.ShellCommon.pri` is because it used to make it so that notif center would work alongside with Win10 Start Menu

To make things more clearer, I'll explain my exact process in the following:
1. I extract 10SM-main.
2. Have C:\Windows open in another window
3. Manually backup/replace files (as some needs perm changes or needs StartMenuExperienceHost.exe to be not running)
4. Double-click `install-classic-start.reg`
5. Sign out and Sign back in

At this point, everything inside Win 10 Start Menu works as expected (except delayed closing out) but notifs and calender stops working. THAT'S the reason why I only (used to) replace `Windows.UI.ShellCommon.pri` to original which would bring back notif center as long as I don't restart the explorer.exe. If explorer.exe is restarted, notif center stays functional but right-clicking apps in Start Menu would crash the Start Menu

The reason why I said "used to" is because now when I tried doing that, the notif center was still broken. So this time I only replaced `Windows.UI.ShellCommon.en-US.pri` instead of `Windows.UI.ShellCommon.pri` assuming I only needed one file to replace back to original. Turns out, you need both of them to be replaced back to original to get back notif center.

Sorry for not keeping track of which winver it was where I only had to replace `Windows.UI.ShellCommon.pri`

But since you got everything working on your end (which is a clean install) and considering the fact that I had things like Start11, and StartIsBack (or something like that; I don't remember) installed previously (even though they were all uninstalled during this experimentation), I think some sort of script, or list of files to clean up whatever 10SM requires to clean up (as in doing whatever is equivalent of clean install) is mandatory. Otherwise I don't think people will clean install Windows 11 just to make this work. It's the reasons like these why I gave up and bought Start11 as a "Set it and forget it" solution but I'm still very happy that you're still working on making this work on most systems. I'll be happy to be a tester for future modifications :)

**Comment by bbmaster123** [comment] 2022-01-25 19:46
thanks for expanding your explanation, just some quick thoughts:
> At this point, everything inside Win 10 Start Menu works as expected (except delayed closing out) but notifs and calender stops working. 

Yea ok so its at this point everything should be working except the close delay as the only remaining bug. right click should work, all tray icons...and it should work through explorer restarts. 

>  Turns out, you need both of them to be replaced back to original to get back notif center.
> yes this is correct

> Sorry for not keeping track of which winver it was where I only had to replace `Windows.UI.ShellCommon.pri`
> all good, I don't think its all that important. What matters is now, and now were on .438 stable. That and making sure the files are all the correct versions and file sizes like you would do anyway.

> But since you got everything working on your end (which is a clean install) 
ehhh I wouldn't quiiite say that, it was installed clean to start but im experimenting and breaking all kinds of things. I mean Ive got snapshots to revert to but ATM its got working start, right click, tray icons, but I borked search, and mica file explorer haha
again Ill have to do a clean install soon of the latest stable release.

> I think some sort of script, or list of files to clean up whatever 10SM requires to clean up (as in doing whatever is equivalent of clean install) is mandatory. Otherwise I don't think people will clean install Windows 11 just to make this work. It's the reasons like these why I gave up and bought Start11 as a "Set it and forget it" solution but I'm still very happy that you're still working on making this work on most systems. I'll be happy to be a tester for future modifications :)

tbf that is the work of a business, not a single dude, to be able to track all the most commonly used programs and monitor the files they change so you can clean it up is just too much for a small project like this where all you do is replace a handful of files.  at least IMO. Don't get me wrong, I would love for this to be set and forget, that'd be awesome, but this is just not that kind of mod. At this stage. this is more for people who actually want to tinker, spend their time learning how it all works, and experiment on their own. Not that you can't set and forget period, but imo the closing delay would drive me mad as a daily driver lol (I'm still on win10 for now)

My ultimate goal is not necessarily to make this perfect, because I probably can't, but if 10SM can make a few people happy, that's pretty cool! 

> I'll be happy to be a tester for future modifications :)
sounds good my friend, drop by any time! :) 
Might be a while, but new stuff is bound to come down the line at some point!

 
cheers man!

**Comment by chuck00000** [comment] 2022-01-28 15:14
> At this point, everything inside Win 10 Start Menu works as expected (except delayed closing out) but notifs and calender stops working. THAT'S the reason why I only (used to) replace `Windows.UI.ShellCommon.pri` to original which would bring back notif center as long as I don't restart the explorer.exe. If explorer.exe is restarted, notif center stays functional but right-clicking apps in Start Menu would crash the Start Menu
> 
> The reason why I said "used to" is because now when I tried doing that, the notif center was still broken. So this time I only replaced `Windows.UI.ShellCommon.en-US.pri` instead of `Windows.UI.ShellCommon.pri` assuming I only needed one file to replace back to original. Turns out, you need both of them to be replaced back to original to get back notif center.
> 
> Sorry for not keeping track of which winver it was where I only had to replace `Windows.UI.ShellCommon.pri`

You're correct, Here's what I  discovered:

1.After replacing the "Windows.UI.ShellCommon.en-US.pri & Windows.UI.ShellCommon.pri , the start menu right click is working, not crashing the start menu; but issues is coming: click Taskbar right corner network & volume icon, date & time; didn't show anything flyouts. then when you continue replace File folder "SystemApps/ShellExperienceHost_cw5n1h2txyewy/ ShellExperienceHost.exe Windows.UI.ActionCenter.dll Windows.UI.QuickActions.dll  Windows.UI.SoftLanding.dll " 4 files, Action (control) center is back! is Win11 flyouts.  click date & time is popped out calendar, after seconds, its crashed & vanish, notification center isn't working, even the notification banners didn't pop out.


2. Don't replace "Windows.UI.ShellCommon.en-US.pri & Windows.UI.ShellCommon.pri" , keep it original, only right click crash the start menu, Action center & notification center works fine, you don't need take any process

**Comment by bbmaster123** [comment] 2022-01-29 00:16
> You're correct, Here's what I discovered:
> 
> 1.After replacing the "Windows.UI.ShellCommon.en-US.pri & Windows.UI.ShellCommon.pri , the start menu right click is working, not crashing the start menu; but issues is coming: click Taskbar right corner network & volume icon, date & time; didn't show anything flyouts. then when you continue replace File folder "SystemApps/ShellExperienceHost_cw5n1h2txyewy/ ShellExperienceHost.exe Windows.UI.ActionCenter.dll Windows.UI.QuickActions.dll Windows.UI.SoftLanding.dll " 4 files, Action (control) center is back! is Win11 flyouts. click date & time is popped out calendar, after seconds, its crashed & vanish, notification center isn't working, even the notification banners didn't pop out.
> 
> 2. Don't replace "Windows.UI.ShellCommon.en-US.pri & Windows.UI.ShellCommon.pri" , keep it original, only right click crash the start menu, Action center & notification center works fine, you don't need take any process

were the 4 shellexperiencehost files you replaced also from build .51? I ask because so far not a single person has confirmed win11 flyouts are working for them, although at the same time, very few have complained about that bug. If most people don't have that bug after all, then I'd want to know what specifically causes it on certain systems.

BTW those 4 files plus the pri files, and a handful of others files can also bring back the windows 10 action center if you use even older versions of those files, but it will break either search, mica file explorer or both. Still experimenting and researching. Just thought Id mention that since you brought up shellexperiencehost.

**Comment by MinerAC4** [comment] 2022-02-10 22:36
I don't have crashing issues, but I am unable to open the action center and system notification

https://user-images.githubusercontent.com/99057951/153508255-9df184c6-a807-488a-87b1-25402dd200dd.mp4

s

**Closed** 2023-09-11 21:14 UTC
