### ISSUE TITLE
Couldn't restore W10 Notification Centre 

### ISSUE THREAD

**Issue by uwuwowowu** [bbmaster123/10SM#5] opened 2021-12-04 15:56 UTC
Hi, i did everything i possibly could to replicate the things shown in the pictures you posted and i could do basically everything except restoring the notification centre.
Is there a way to fully restore that notification centre with everything working as it did in windows 10? 

Thank you anyway for your work because i was able to fully restore the start menu i loved for free :)

**Comment by bbmaster123** [comment] 2021-12-04 16:22
so far no, not yet. Its restorable but not everything works at this moment, though some things do. It also has the same exit delay bug the the start menu has right now, which I believe I'm closing in on the root cause yay :)

I'll post back here if I make any progress. I'm glad you're enjoying the start menu!
cheers

**Closed** 2021-12-28 06:14 UTC
